[build-system]
requires = ["hatchling",
            "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "ai-community-observer"
version = "0.4.0"
description = "A tool for autonomously observing and analyzing AI applications"
readme = "README.md"
requires-python = ">=3.8"
license = "Apache-2.0"
authors = [
  { name="James Drayton Beninger", email="jamesdrayton18@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
dependencies = [
  "google-genai>=2.11.0",
  "openai>=2.45.0",
  "huggingface-hub>=0.34.4",
  "scikit-learn>=1.6.1",
  "httpx>=0.28.1",
  "python-dotenv>=1.0.0",
]
license-files = ["LICEN[CS]E*"]

[project.optional-dependencies]
fastapi = [
  "fastapi[standard]>=0.111.1"
]

[project.urls]
Homepage = "https://github.com/jamesdrayton/AICommunityObserver"
Documentation = "https://github.com/jamesdrayton/AICommunityObserver#readme"
Issues = "https://github.com/jamesdrayton/AICommunityObserver/issues"
Source = "https://github.com/jamesdrayton/AICommunityObserver"

[tool.hatch.build.targets.wheel]
packages = ["src/AICommunityObserver"]

[project.entry-points."aicommunityobserver.metrics"]